### PR TITLE
Added the `catimage` cdn & fixed readme

### PR DESCRIPTION
**Pull request by Yasha-Grachova**
# catimage
the cdn for the best cats

### CODE REVIEW

**Comment by lgrachov** [comment]
this is a **pretty good** CDN for the cats.
But you need to provide different links!

**Comment by Yasha-Grachova** [comment]
oh .

**Comment by Yasha-Grachova** [comment]
we need to PROVIDE LINKS????

**Comment by lgrachov** [comment]
So I made the links from the pull request:
***
/serious.jpeg

/domestic.jpeg


/better/wantsfood.jpeg

/better/sleeping.jpeg

/better/sitting.jpeg

**Comment by lgrachov** [comment]
Also I've seen you fixed the readme, congratulations!

**Review by lgrachov — CHANGES_REQUESTED** [review]
You must replace the *how it works* before merging.

**Comment by Yasha-Grachova** [comment]
> You must replace the _how it works_ before merging.

im ready

**Pull request merged**
